name: Build

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Test
      run: make build test

    - name: Distribution
      run: make distribution
      if: startsWith(github.ref, 'refs/tags/')
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          release/webhookd-linux-amd64.tgz
          release/webhookd-linux-arm64.tgz
          release/webhookd-linux-arm.tgz
          release/webhookd-darwin-amd64.tgz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
